/**
 * Extended Database Types for Supabase
 *
 * Pattern from Supabase docs: https://supabase.com/docs/guides/api/rest/generating-types
 * "Enhanced type inference for JSON fields" (supabase-js v2.48.0+)
 *
 * This file extends the autogenerated database.types.ts with specific types
 * for JSONB columns, providing better type safety when working with JSON fields.
 */

import { MergeDeep } from 'type-fest';
import { Database as DatabaseGenerated } from './database.types';

// ============================================================================
// JSON FIELD TYPES
// Define specific TypeScript types for data stored in JSONB columns
// ============================================================================

/**
 * Geolocation coordinates - used in time_entries.location
 */
export interface GeoLocation {
  latitude: number;
  longitude: number;
}

/**
 * Employee availability schedule - used in employees.availability
 */
export interface AvailabilitySchedule {
  [dayOfWeek: string]: {
    available: boolean;
    start?: string; // HH:MM format
    end?: string;   // HH:MM format
  };
}

// ============================================================================
// EXTENDED DATABASE TYPE
// Merge the autogenerated types with our specific JSON types
// ============================================================================

export type Database = MergeDeep<
  DatabaseGenerated,
  {
    public: {
      Tables: {
        // Extend employees table with typed availability field
        employees: {
          Row: {
            availability: AvailabilitySchedule | null;
          };
          Insert: {
            availability?: AvailabilitySchedule | null;
          };
          Update: {
            availability?: AvailabilitySchedule | null;
          };
        };
        // Extend time_entries table with typed location field
        time_entries: {
          Row: {
            location: GeoLocation | null;
          };
          Insert: {
            location?: GeoLocation | null;
          };
          Update: {
            location?: GeoLocation | null;
          };
        };
      };
    };
  }
>;

// Re-export the Json type for compatibility
export type { Json } from './database.types';
